### ISSUE TITLE
Bug with test-image.py

### ISSUE THREAD

**Issue by l333wang** [Lornatang/SRCNN-PyTorch#1]
The example of running test-image.py is not correct. There is no arguments of scale factor and device.

**Comment by Lornatang** [comment]
Ok,Thanks. @l333wang

**Comment by Lornatang** [comment]
@l333wang Hi, wang.I'm too busy to fix this error. I'm too busy to fix it.

**Comment by chensguo8099** [comment]
> The example of running test-image.py is not correct. There is no arguments of scale factor and device.

sorry, Have you solved this problem? I also can't run the code test-image.py

**Comment by l333wang** [comment]
> > The example of running test-image.py is not correct. There is no arguments of scale factor and device.
> 
> **@I333wang** sorry, Have you solved this problem? I also can't run the code test-image.py

I didn't solve this problem. I suggest you by simply adding the argument and set default value to this code to see if this can be solved.

**Comment by l333wang** [comment]
> @l333wang Hi, wang.I'm too busy to fix this error. I'm too busy to fix it.

no worries, I just want to let you know.

**Comment by Lornatang** [comment]
I fixed it.
