### ISSUE TITLE
关于数据前处理的

### ISSUE THREAD

**Issue by SailVR** [Lornatang/SRCNN-PyTorch#3]
您好，能提供下数据前处理的文件吗？就是把图片切割成41×41的块和保存为lmdb格式的

**Comment by SailVR** [comment]
你的好几个关于超分的网络都很好，复现都很棒。但是数据下载确实太大了，百度网盘下载速度也慢，我还是觉得自己这边下好了开源的数据集，直接用处理好的文件生成想要的格式，再塞入网络进行训练。这样速度会快很多

**Comment by Lornatang** [comment]
谢谢，自己制作就好了，半个小时就制作完了
