### ISSUE TITLE
SSIM Metric Calculation

### ISSUE THREAD

**Issue by muhammetbolat** [Lornatang/SRCNN-PyTorch#5]
Hello Lornatang,

I am a little bit confused to calculate SSIM metric for this project. If it is possible, can you share with me the SSIM code calculation code for SRCNN? 

Thanks in advanced.

**Comment by Lornatang** [comment]
I have written evaluation metrics like PSNR, SSIM etc for my other projects, you can visit https://github.com/Lornatang/SRGAN-PyTorch/blob/main/image_quality_assessment.py

**Comment by muhammetbolat** [comment]
thank you. It works :)
